stages:
  - download_and_install
  - build_apk
install_tools_etc:
  stage: download_and_install
  script:
    - echo "Installing software-properties-common."
    - sudo apt-get --assume-yes install software-properties-common
    - sudo add-apt-repository ppa:lyzardking/ubuntu-make
    - sudo apt-get update
    - sudo apt-get --assume-yes install ubuntu-make
    - echo "\android-sdk" | umake android android-sdk --accept-license
    - echo "\dart" | umake dart
    
    - mkdir "/dev"
    - mkdir "/flutter"
    - git clone -b master --depth 1 https://github.com/flutter/flutter.git flutter
    - cd "/flutter"
    - ls
    - export PATH=`pwd`/flutter/bin:$PATH
    - cd "/"
    - ls
    - flutter doctor
    - flutter build apk
  