#image: martinlowinski/flutter-android-sdk not working
image: mattclark/flutter-build-docker
testing:
  stage: build
  script:
  - ls
  - echo "Building the APK"
  - flutter build apk
  - echo "Done building the APK"